# Generated by Django 5.2.4 on 2025-07-03 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('address', models.TextField()),
                ('debt', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('import_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('export_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
