# Generated by Django 5.2.4 on 2025-07-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customer_branch_products_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
