# Generated by Django 5.2.4 on 2025-07-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_crated_at_products_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
